###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /var/www/html
        volumes:
            - 'database_data:/var/lib/mysql:delegated'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=article
            - MYSQL_USER=root_user
            - MYSQL_PASSWORD=root_password
        ports:
            - '64002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '64000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        platform: linux/amd64
        environment:
            - PMA_HOST=mysql
        restart: always
        ports:
            - '64001:80'
        links:
            - mysql:db
        volumes:
            - './phpdocker/phpmyadmin/docker.user.inc.php:/docker.user.inc.php'
        depends_on:
            - mysql
###############################  Volumes  ###############################

volumes:
    database_data: